stac/southland/invercargill_2022_0.1m/rgb/2193/collection.json
https://data.linz.govt.nz/layer/110773-invercargill-01m-urban-aerial-photos-2022/
=> fix(southland): invercargill 2022 0.1m coverage name differes to LDS

.github/workflows/publish-to-odr.yml, publish-odr-parameters/README.md
changed from skip ci in [ ] to `[skip-workflows]` in the PR title
Now the publish workflow will still run (which is required for a merge to master) but the publish-odr workflow can still be skipped using a similar logic.
=> feat: add skip-workflows option [skip-argo]

publish-odr-parameters/2023/hurunui_2023_0.075m.yaml
to get the publish-odr action to trigger after fixing a bug this file had to be modified. 
This pr is just reverting this change back to correct formatting - publish-odr will not be triggered.
=> fix: revert temp change to trigger action [skip-argo]

.github/workflows/create-pr.yml, .github/workflows/publish-to-odr.yml, .github/workflows/publish.yml
Done with pin-github-action <https://github.com/mheap/pin-github-action> 1.8.0 using `npx pin-github-action .github/workflows/*.yml`.
Dependabot should support updating in the same fashion <https://github.com/dependabot/dependabot-core/issues/8277#issuecomment-1782819752>.
Had to `export GH_ADMIN_TOKEN=github_pat_…` using a fine-grained personal access tokens with no extra access to work around rate limiting *and* to be able to work in private repos
<https://github.com/mheap/pin-github-action/issues/73>.
=> feat: Pin actions to hashes TDE-934

.github/workflows/publish.yml
The STAC Catalog was not validated. This doesn't validate the collection links, but it does check the structure of the catalog is valid.
=> fix: validate STAC Catalog TDE-967

publish-odr-parameters/README.md
The publish-odr workflow has been upated to now take the target bucket name and then automatically generate the target path based on the collection parameters. Therefore the documentation here needed to be updated accordingly
=> docs: update publish-odr documentation TDE-955

docs/usage.md
Fixes grammar and typos identified when porting across to linz/elevation
=> docs: fix grammar / typos in usage.md

.github/workflows/publish.yml
The logic to use `$base` (the name of the parameters.yaml file) to name the argo workflow submitted no longer works. 
https://github.com/linz/imagery/actions/runs/8413556393
This change will give each submission the name `publish-odr-`
In future we could update this to include the name of the branch/pull request however as the action is currently broken this is the quickest solution.
=> ci: remove parameters yaml filename

.github/workflows/publish.yml
The collection will be "synced" later on this workflow and include any changed made in the PR that will not be in the `/flat/` directory. Therefore we should exlude it here.
=> ci: exclude collection.json

publish-odr-parameters/01HSSD824MS222RR0W044QZADV-1711327325496.yaml
Retry the copy of the 2020-2021 satellite imagery. It should not try to copy the `collection.json` file from the scratch bucket location.
=> fix: copy without failing on collection.json TDE-1107

.github/workflows/publish.yml
make the name of the workflow unique so that it can be distinguished from publish-odr workflows run through other means.
=> ci: update generate-name parameter TDE-1058

stac/bay-of-plenty/bay-of-plenty_2023-2024_0.2m/rgb/2193/collection.json
At time of import, category was updated to `rural-aerial-photos` from `urban-aerial-photos`, however the title of the dataset was not updated.
This fix will make the title consistent with the category.
=> fix: correct category in title to match dataset category

stac/bay-of-plenty/bay-of-plenty_2023-2024_0.2m/rgb/2193/collection.json
Changing producer from Aerial Surveys to Woolpert.
=> fix: correct producer of bay-of-plenty_2023-2024_0.2m

.github/workflows/publish.yml, package-lock.json, package.json
Depends on #420.
1. Update the engine:
```
jq '.engines.node = "^20.13.1"' package.json | sponge package.json
```
2. Update the lock file:
```
npm install
```
3. Update the uses of `linz/action-typescript`:
```
for path in .github/workflows/*.y*ml; do
yq --inplace '(.jobs.*.steps[] | select(.uses == "linz/action-typescript*").with.node-version) = "20.x"' "$path";
done
```
=> build: Bump Node.js to latest LTS, 20.13.1 TDE-1090

.github/pull_request_template.md, .github/workflows/publish.yml
When jobs are rerun STAC documents can be synced into s3 from a old pull request
- allows workflows to be run without a commit merged to ensure stac is upto date
- Force checkout master when syncing stac so only the latest versions are synced.
=> fix: ensure only the latest stac documents are synced into s3

stac/auckland/auckland-coast_2022-2023_0.05m/rgb/2193/collection.json, stac/auckland/auckland-coast_2023_0.05m/rgb/2193/collection.json
The title is missing the metre symbol following the GSD in the dataset's title.
=> fix: add metre symbol to gsd in title

README.md
STAC Index is using an older version of STAC Browser that isn't as easy to browse through. We've received feedback that the previous link was more helpful.
Reverted browsing links to go to STAC Browser rather than STAC Index.
Added a badge + link through to Registry of Open Data on AWS.
=> docs: revert to STAC Browser for browsing the catalog

.github/CODEOWNERS
Data managers need to be able to approve the addition of new Imagery datasets.
Added the Imagery team as CODEOWNERS of `publish-odr-parameters` in addition to the `stac` dir.
N/A
=> chore: add publish-odr-parameters owners to CODEOWNERS

stac/bay-of-plenty/tauranga-winter_2022_0.1m/rgb/2193/collection.json
Original title belongs to [tauranga_2022_0.1m](https://github.com/linz/imagery/blob/master/stac/bay-of-plenty/tauranga_2022_0.1m/rgb/2193/collection.json)
=> fix: tauranga-winter_2022_0.1m title

stac/canterbury/waimate_2021_0.075m/rgb/2193/collection.json
Year in title was 2021-2022, should just be 2021.
Path contains correct year and flown dates are in 2021. This will make it consistent with LDS title too.
=> fix: fixed year in waimate_2021_0.075m title

stac/canterbury/waimakariri_2025_0.04m/rgb/2193/collection.json
`BW23_500_044097` JSON item link needs to be removed from the collection as the TIFF does not exist (was outside the cutline).
=> fix: remove collection link to BW23_500_044097.json item TDE-1669
